services:

  # Gateway
  nginx:
    container_name: nginx
    image: nginx:1.29-alpine-slim
    restart: always
    networks:
      - mainnet
    volumes:
      - ./services/nginx/config/:/etc/nginx/conf.d/
      - ./services/nginx/routes/:/etc/nginx/routes.d/
      - ./services/nginx/rules/:/etc/nginx/rules.d/
      - ./frontend/dist/:/var/www/html/
    secrets:
      - ssl_key
      - ssl_certificate
    ports:
      - "8443:443"
    depends_on:
      - auth-backend
      - kibana

  # RabbitMQ
  broker:
    container_name: broker
    image: rabbitmq:4.1.1-management-alpine
    restart: always
    networks:
      - mainnet
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    env_file:
      - ".env"
    expose:
      - 5672
      - 15672

  # ELK
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.0
    restart: always
    networks:
      - mainnet
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
    depends_on:
      - logstash

  logstash:
    container_name: logstash
    image: logstash:8.12.0
    restart: always
    networks:
      - mainnet
    volumes: 
      - "./logs:/var/log/services"
      - "./services/ELK/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./services/ELK/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    expose: 
      - 5044

  kibana:
    container_name: kibana
    image: kibana:8.12.0
    restart: always
    networks:
      - mainnet
    ports: 
      - 5601
    depends_on:
      - elasticsearch

  # HashiCorp Vault
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    restart: always
    env_file:
      - .env
    networks:
      - mainnet
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id="$VAULT_DEV_ROOT_TOKEN_ID"
    volumes:
      - ./services/vault/config:/vault/config
      - ./services/vault/data:/vault/data
      - ./logs:/vault/logs
    ports:
      - "8200:8200"

  vault-init:
    image: hashicorp/vault:1.16
    env_file:
      - .env
    networks:
      - mainnet
    volumes:
      - ./services/vault/scripts/jwt_vault.sh:/jwt_vault.sh
    environment:
      VAULT_ADDR: "http://vault:8200"
    entrypoint: /jwt_vault.sh
    depends_on:
      - vault

  # Backend
  auth-backend:
    container_name: auth-backend
    env_file:
      - .env
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    restart: always
    networks:
      - mainnet
    volumes:
      - ./logs:/logs
      - ./data/auth:/prisma/db
    environment:
      NODE_ENV: production
    depends_on:
      - vault
    expose:
      - 3000

networks:
  mainnet:
    driver: bridge

volumes:
  rabbitmq-lib:
    driver: local

  rabbitmq-log:
    driver: local

secrets:
  ssl_key:
    file: ./secrets/ssl/nginx-selfsigned.key

  ssl_certificate:
    file: ./secrets/ssl/nginx-selfsigned.crt