services:

  # TLS Terminate Point
  nginx-ssl:
    container_name: nginx-ssl
    image: nginx:1.29-alpine-slim
    restart: always
    env_file:
      - env/.no_sensitive.env
    networks:
      - dmz-net
    environment:
      - WAF_ADDR=http://nginx-waf:8080
    volumes:
      - ./services/nginx/shared/rules.d/:/etc/nginx/rules.d/:ro
      - ./services/nginx/ssl/templates/:/etc/nginx/templates/:ro
      - ./services/nginx/ssl/includes/:/etc/nginx/includes/:ro
      - ./logs/nginx_ssl/:/var/log/nginx:rw
    secrets:
      - ssl-cert
      - ssl-key
    ports:
      - "8443:443"
    depends_on:
      nginx-waf:
        condition: service_started

  # WAF
  nginx-waf:
    container_name: nginx-waf
    build:
      context: ./services/nginx/
      dockerfile: ./waf/Dockerfile
    restart: always
    env_file:
      - env/.no_sensitive.env
    networks:
      - dmz-net
    environment:
      - API_GATEWAY_ADDR=http://nginx-gateway:8080
    expose:
      - 8080
    depends_on:
      nginx-gateway:
        condition: service_started

  # Gateway
  nginx-gateway:
    container_name: nginx-gateway
    image: nginx:1.29-alpine-slim
    restart: always
    env_file:
      - env/.no_sensitive.env
    networks:
      - mainnet
      - dmz-net
      - vault-net
    volumes:
      - ./services/nginx/shared/rules.d/:/etc/nginx/rules.d/:ro
      - ./services/nginx/gateway/routes.d/:/etc/nginx/routes.d/:ro
      - ./services/nginx/gateway/templates/:/etc/nginx/templates/:ro
      - ./logs/nginx_gateway/:/var/log/nginx/:rw
    expose:
      - 8080
    depends_on:
      frontend:
        condition: service_started
      kibana:
        condition: service_healthy
      minio:
        condition: service_started
      broker:
        condition: service_healthy
      vault:
        condition: service_healthy
      lab:
        condition: service_started
      auth-backend:
        condition: service_started
      users-backend:
        condition: service_started

  # Frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - env/.no_sensitive.env
    networks:
      - mainnet
    volumes:
      - ./logs/frontend/:/var/log/nginx/:rw
    expose:
      - 8080
    depends_on:
      auth-backend:
        condition: service_started
      users-backend:
        condition: service_started

  # S3
  minio:
    container_name: minio
    build:
      context: ./services/s3
      dockerfile: Dockerfile
    restart: always
    env_file:
      - env/.s3.env
    networks:
      - mainnet
    volumes:
      - ./data/minio/:/data/:rw
      - ./assets/minio/:/init-assets/:ro
    command: server /data --console-address ":9001"
    expose:
      - 9000
      - 9001

  # RabbitMQ
  broker:
    container_name: broker
    image: rabbitmq:4.1.1-management-alpine
    restart: always
    env_file:
      - env/.broker.env
    networks:
      - mainnet
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 30s
    expose:
      - 5672
      - 15672

  # ELK
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./services/ELK/elasticsearch/
      dockerfile: Dockerfile
    restart: always
    networks:
      - elk-net
    env_file:
      - env/.elastic.env
      - env/.kibana.env
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
      - elasticsearch-log:/usr/share/elasticsearch/logs:rw
    healthcheck:
      test: ["CMD", "/usr/share/elasticsearch/bin/healthcheck-wrapper.sh"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 30s
    expose:
      - 9200

  logstash:
    container_name: logstash
    image: logstash:8.12.0
    restart: always
    networks:
      - elk-net
    env_file:
      - env/.elastic.env
    volumes: 
      - ./logs/:/var/log/services/:ro
      - ./services/ELK/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./services/ELK/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    expose:
      - 5044
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:9600/_node/pipelines"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 30s
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    container_name: kibana
    build:
      context: ./services/ELK/kibana
      dockerfile: Dockerfile
    restart: always
    networks:
      - mainnet
      - elk-net
    env_file:
      - env/.no_sensitive.env
      - env/.kibana.env
    expose:
      - 5601
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://kibana:5601/api/status"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 30s
    depends_on:
      elasticsearch:
        condition: service_healthy

  # HashiCorp Vault
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    restart: always
    env_file:
      - env/.vault.env
    networks:
      - vault-net
      - vault-init-net
    volumes:
      - ./services/vault/scripts/vault_server.sh:/vault_server.sh:ro
      - ./services/vault/config:/vault/config:ro
      - ./data/vault/:/vault/data/:rw
      - ./logs/vault/:/vault/logs/:rw
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: /vault_server.sh
    expose:
      - 8200
    healthcheck:
      test: ["CMD-SHELL", "vault status > /dev/null 2>&1"]
      interval: 1s
      timeout: 2s
      retries: 20
      start_period: 40s

  vault-init:
    image: hashicorp/vault:1.16
    restart: 'no'
    env_file:
      - env/.vault.env
      - env/.token.env
    networks:
      - vault-init-net
    volumes:
      - ./services/vault/scripts/vault_init.sh:/vault_init.sh:ro
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: /vault_init.sh
    depends_on:
      vault:
        condition: service_healthy

  # Test Infra
  lab:
    container_name: lab
    build:
      context: ./services/lab
      dockerfile: Dockerfile
    networks:
      - mainnet
    volumes:
      - ./logs/lab:/logs/:rw
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  # Backend
  auth-backend:
    container_name: auth-backend
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    env_file:
      - env/.vault.env
      - env/.google.env
      - env/.broker.env
    restart: always
    networks:
      - mainnet
      - vault-net
    volumes:
      - ./logs/auth-backend/:/logs/:rw
      - ./data/auth-backend/:/prisma/db/:rw
    environment:
      - NODE_ENV=production
    depends_on:
      vault:
        condition: service_started
      broker:
        condition: service_healthy
    expose:
      - 3000

  users-backend:
    container_name: users-backend
    build:
      context: ./services/users
      dockerfile: Dockerfile
    env_file:
      - env/.s3.env
      - env/.broker.env
      - env/.no_sensitive.env
    restart: always
    networks:
      - mainnet
    volumes:
      - ./logs/users-backend/:/logs/:rw
      - ./data/users-backend/:/prisma/db/:rw
    environment:
      - NODE_ENV=production
    depends_on:
      auth-backend:
        condition: service_started
      minio:
        condition: service_started
      vault:
        condition: service_healthy
      broker:
        condition: service_healthy
    expose:
      - 3000

networks:
  dmz-net:
    driver: bridge

  mainnet:
    driver: bridge

  elk-net:
    driver: bridge
    internal: true

  vault-net:
    driver: bridge
    internal: true

  vault-init-net:
    driver: bridge
    internal: true

volumes:
  rabbitmq-lib:
    driver: local

  rabbitmq-log:
    driver: local

  elasticsearch-data:
    driver: local

  elasticsearch-log:
    driver: local

secrets:
  ssl-cert:
    file: ./secrets/ssl/server.crt

  ssl-key:
    file: ./secrets/ssl/server.key
