services:

  # Gateway
  nginx-gateway:
    container_name: nginx-gateway
    image: nginx:1.29-alpine-slim
    restart: always
    networks:
      - mainnet
      - vault-net
    volumes:
      - ./services/nginx_gateway/config/:/etc/nginx/conf.d/
      - ./services/nginx_gateway/routes/:/etc/nginx/routes.d/
      - ./services/nginx_gateway/rules/:/etc/nginx/rules.d/
      - ./logs/nginx_gateway/:/var/log/nginx/
    secrets:
      - ssl_key
      - ssl_certificate
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - kibana
      - lab
      - auth-backend

  # Frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - mainnet
    volumes:
      - ./logs/frontend/:/var/log/nginx/
    expose:
      - 8080

  # RabbitMQ
  broker:
    container_name: broker
    image: rabbitmq:4.1.1-management-alpine
    restart: always
    networks:
      - mainnet
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    env_file:
      - .env
    expose:
      - 5672
      - 15672

  # ELK
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.0
    restart: always
    networks:
      - elk-net
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
    depends_on:
      - logstash

  logstash:
    container_name: logstash
    image: logstash:8.12.0
    restart: always
    networks:
      - elk-net
    volumes: 
      - ./logs/:/var/log/services/
      - ./services/ELK/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./services/ELK/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    expose: 
      - 5044

  kibana:
    container_name: kibana
    image: kibana:8.12.0
    restart: always
    networks:
      - mainnet
      - elk-net
    ports: 
      - 5601
    depends_on:
      - elasticsearch

  # HashiCorp Vault
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    restart: always
    env_file:
      - .env
    networks:
      - vault-net
      - vault-init-net
    volumes:
      - ./services/vault/config:/vault/config
      - ./data/vault/:/vault/data/
      - ./logs/vault/:/vault/logs/
      - ./services/vault/scripts/vault_server.sh:/vault_server.sh
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: /vault_server.sh
    ports:
      - 8200

  vault-init:
    image: hashicorp/vault:1.16
    env_file:
      - .env
    networks:
      - vault-init-net
    volumes:
      - ./services/vault/scripts/vault_init.sh:/vault_init.sh
    environment:
      - VAULT_ADDR=http://vault:8200
    entrypoint: /vault_init.sh
    depends_on:
      - vault

  # Test
  lab:
    container_name: lab
    build:
      context: ./services/labratory
      dockerfile: Dockerfile
    networks:
      - mainnet
    volumes:
      - ./logs/lab:/logs/
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  # Backend
  auth-backend:
    container_name: auth-backend
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - mainnet
      - vault-net
    volumes:
      - ./logs/auth-backend/:/logs/
      - ./data/auth/:/prisma/db/
    environment:
      - NODE_ENV=production
    depends_on:
      - vault
    expose:
      - 3000

networks:
  mainnet:
    driver: bridge

  elk-net:
    driver: bridge

  vault-net:
    driver: bridge

  vault-init-net:
    driver: bridge

volumes:
  rabbitmq-lib:
    driver: local

  rabbitmq-log:
    driver: local

secrets:
  ssl_key:
    file: ./secrets/ssl/nginx-selfsigned.key

  ssl_certificate:
    file: ./secrets/ssl/nginx-selfsigned.crt