# Port
listen 443 ssl;
listen [::]:443 ssl;

# SSL
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_certificate     /etc/nginx/ssl/server.crt;
ssl_certificate_key /etc/nginx/ssl/server.key;

# Modsecurity
modsecurity             on;
modsecurity_rules_file  /etc/nginx/modsecurity.d/basic_rule.conf;
