input {

  file {
    path => "/var/log/services/**/*.log"
    start_position => "beginning"
    codec => "json"
    sincedb_path => "/dev/null"
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "transcendence-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }

}
