input {

  file {
    path => "/var/log/services/**/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }

}

filter {

    # Try JSON decode first
    json {
        source => "message"
        skip_on_invalid_json => true
    }

    if "_jsonparsefailure" in [tags] {
        mutate { remove_tag => ["_jsonparsefailure"] }

        # Try access log format
        grok {
            match => { "message" => [
                '%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{URIPATH:request}(?:%{URIPARAM:query_string})? HTTP/%{NUMBER:http_version}" %{NUMBER:status:int} (?:%{NUMBER:bytes:int}|-)(?: "%{URI:referrer}" "%{DATA:user_agent}")?'
            ]}
            overwrite => [ "message" ]
        }

        date {
            match => ["timestamp", "dd/MMM/YYYY:HH:mm:ss Z"]
            target => "@timestamp"
            timezone => "UTC"
        }

        # If still no grok match, try Nginx error log
        if "_grokparsefailure" in [tags] {

            mutate { remove_tag => ["_grokparsefailure"] }

            grok {
                match => { "message" => [
                # Example: 2025/07/17 09:48:39 [notice] 1#1: signal 17 (SIGCHLD) received from 35
                '%{YEAR:year}/%{MONTHNUM:month}/%{MONTHDAY:day} %{TIME:time} \[%{LOGLEVEL:log_level}\] %{GREEDYDATA:nginx_message}'
                ]}
            }

            mutate {
                add_field => { "timestamp" => "%{year}/%{month}/%{day} %{time}" }
            }

            date {
                match => ["timestamp", "YYYY/MM/dd HH:mm:ss"]
                target => "@timestamp"
                timezone => "UTC"
            }
            
        }

    }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "transcendence-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }

}
