server {
    # Port
    listen 443 ssl;
    listen [::]:443 ssl;

    # SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /run/secrets/ssl_certificate;
    ssl_certificate_key /run/secrets/ssl_key;

    # Main properties
    root /var/www/html;
    server_name localhost;
    index index.html index.htm;

    # Block illegal url
    include /etc/nginx/rules.d/forbidden-urls-rule.conf;

    # For proxy routing to all services
    include /etc/nginx/routes.d/*.conf;

    # For fetching frontend page
    location / {
        try_files $uri $uri/ =404;
    }

    # Logs
    access_log /var/log/nginx/nginx_default_access.log;
    error_log /var/log/nginx/nginx_default_error.log;
}