server {
    # Port
    listen 443 ssl;
    listen [::]:443 ssl;

    # SSL
    ssl_certificate     /run/secrets/ssl_certificate;
    ssl_certificate_key /run/secrets/ssl_key;

    # Main properties
    server_name kibana.localhost;

    # Route to kibana service
    location / {
        proxy_pass http://kibana:5601;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Logs
    access_log /var/log/nginx/nginx_elk_access.log;
    error_log  /var/log/nginx/nginx_elk_error.log;
}