server {
    # Port
    listen 443 ssl;
    listen [::]:443 ssl;

    # SSL
    ssl_certificate     /run/secrets/ssl_certificate;
    ssl_certificate_key /run/secrets/ssl_key;

    # Main properties
    server_name vault.localhost;

    # Block illegal url
    include /etc/nginx/rules.d/forbidden-urls-rule.conf;

    # Block vault's api
    location /v1/ {
        deny all;
        return 403;
    }

    # Route to service
    location / {
        include /etc/nginx/rules.d/generic-proxy-rule.conf;
        proxy_pass http://vault:8200;
    }

    # Logs
    access_log /var/log/nginx/nginx_vault_access.log;
    error_log  /var/log/nginx/nginx_vault_error.log;
}