server {
    # Port
    listen 443 ssl;
    listen [::]:443 ssl;

    # SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /run/secrets/ssl_certificate;
    ssl_certificate_key /run/secrets/ssl_key;

    # Main properties
    server_name localhost;

    # Block illegal url
    include /etc/nginx/rules.d/forbidden-urls-rule.conf;

    # Route to auth service
    location /auth/ {
        proxy_pass http://auth-backend:3000;
        include /etc/nginx/rules.d/restful-proxy-rule.conf;
    }

    # Route to frontend service
    location / {
        proxy_pass http://frontend:8080;
        include /etc/nginx/rules.d/restful-proxy-rule.conf;
    }

    # Logs
    access_log /var/log/nginx/nginx_default_access.log;
    error_log /var/log/nginx/nginx_default_error.log;
}