server {
    # Port
    listen 80;
    listen [::]:80;

    # Main properties
    root /var/www/html;
    server_name localhost;
    index index.html index.htm;

    # For fetching frontend page
    location / {
        try_files $uri $uri/ =404;
    }

    # Logs
    access_log /var/log/nginx/nginx_frontend_access.log;
    error_log /var/log/nginx/nginx_frontend_error.log;
}